L2ACIP-243: Added tests
magento-sparta/m2-convert-patch-for-composer-install pull request #11
Opened 2024-04-22 19:22 UTC by katmoon

Many extensions must be added to the converter, but the lack of tests complicates testing changes.

* Minimal changes were made to decouple converter logic from console processing to enable unit testing.
* Converter logic has not been changed.

2024-04-23 21:26 UTC, soklymeach approved these changes

2024-04-24 15:20 UTC, agorbivskyi commented on src/Converter.php
> +}
Please add a new line here.

2024-04-24 15:20 UTC, agorbivskyi commented on tests/ConverterTest.php
> +}
Please add a new line here.

2024-04-24 15:20 UTC, agorbivskyi requested changes
Please add a new line in mentioned files.

2024-04-24 16:43 UTC, agorbivskyi approved these changes

2024-04-24 16:43 UTC, merged